// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Bb9FW5gH7rDbSYEah9JLsgs2fFKCanQ',
    appId: '1:534807315581:web:cdbe725c20f3ca6a7d5d14',
    messagingSenderId: '534807315581',
    projectId: 'spotify-app-71669',
    authDomain: 'spotify-app-71669.firebaseapp.com',
    storageBucket: 'spotify-app-71669.appspot.com',
    measurementId: 'G-PCEL6504RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlsReDMJCbH0hLTWLwSnIwPD0LqZK0dk',
    appId: '1:534807315581:android:71da11cdfe7fcffa7d5d14',
    messagingSenderId: '534807315581',
    projectId: 'spotify-app-71669',
    storageBucket: 'spotify-app-71669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRc96QNg7x391SU8EGkA66Gj-WQuFd9mY',
    appId: '1:534807315581:ios:11393e490e3749f37d5d14',
    messagingSenderId: '534807315581',
    projectId: 'spotify-app-71669',
    storageBucket: 'spotify-app-71669.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRc96QNg7x391SU8EGkA66Gj-WQuFd9mY',
    appId: '1:534807315581:ios:11393e490e3749f37d5d14',
    messagingSenderId: '534807315581',
    projectId: 'spotify-app-71669',
    storageBucket: 'spotify-app-71669.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Bb9FW5gH7rDbSYEah9JLsgs2fFKCanQ',
    appId: '1:534807315581:web:51159fcb6961f39f7d5d14',
    messagingSenderId: '534807315581',
    projectId: 'spotify-app-71669',
    authDomain: 'spotify-app-71669.firebaseapp.com',
    storageBucket: 'spotify-app-71669.appspot.com',
    measurementId: 'G-4HEHBMESBR',
  );
}
